name = "store-viewer"
version = "0.1.0"
component = "/Users/colinrozzi/work/actor-registry/store-viewer/./target/wasm32-unknown-unknown/release/store_viewer.wasm"
description = "Theater store label viewer/editor"
save_chain = true

[[handler]]
type = "runtime"

[[handler]]
type = "http-framework"

[[handler]]
type = "store"
